### ISSUE TITLE
3x (9x) tech mod WK doesnt work properly on linux

### ISSUE THREAD

**Issue by DjSapsan** [SiegeEngineers/WololoKingdoms#44]
Im on Linux Mint. First i used the AoE2ToolsCloud to install WK. Everything is absolutely fine. After first start i got some successful updates. Mods are working just fine. I got "WK", "Realms" and regular "3x tech" mod by default in AoE2Tools.
After some games i wanted to install other mods. As i expected, native Linux Chrome could not install mods for voobly on wine. So i downloaded this WK and used checkbox to install mods. First i installed "3x tech mod WK" and its didnt work. I was crashed in first minutes of multiplayer. I tested in singleplayer and i got only 1 regular tech. After i installed the "9x tech mod WK" and as before i didnt get more techs, just single one. 
Also i can join as a spectator and watch first seconds before stop. I believe, when someone starts to upgrade loom im just desync as the spectator.
![qwer](https://user-images.githubusercontent.com/12209464/66082703-5dd8cd80-e573-11e9-9790-2e9f2207f4ca.png)

**Comment by DjSapsan** [comment]
![image](https://user-images.githubusercontent.com/12209464/66082915-db9cd900-e573-11e9-82ac-502ad3e040b6.png)

**Comment by gregstein** [comment]
The desync is most likely due to the data mods being a different version than the others. Which is why I  highly recommended WK Installer to install 'Data Mods' as preview in the imagery above.

**Comment by DjSapsan** [comment]
Im using latest version of the WK installer. Is there a way to install mods by copying folders? I want to install different mods form voobly workshop.
If it is not possible i'll also try to use Internet Explorer on wine. 
My ultimate idea is to make all people switch to Linux, and i preparing simple tutorials for it.

**Comment by gregstein** [comment]
Yes it is possible. Some mods such as x3 Tech will additionally need symbolic linking to WK (or else add the rest of WK files to the mod folder by copying them over - Not recommended because it'll take much space)

However the visual mods are small in filesize so you can basically install them by yourself all through voobly in a windows OS then use AoE2Tools > Manager > to back them up 

![aoe2tools-manager](https://user-images.githubusercontent.com/16618729/66124409-3407c100-e5dc-11e9-93aa-68676e8f114a.png)


Then provide a download link in the description of your video which users can easily import that zip file containing all mods

![aoe2tools-manager-restore](https://user-images.githubusercontent.com/16618729/66124445-50a3f900-e5dc-11e9-835e-e48295e1e7b6.png)


Now that Im talking about this I may consider an update to AoE2Tools where users can install any voobly visual mods through aoe2tools itself. It'll take time to achieve though but I will consider it.

Not sure if you have seen this linux guide yet, but here https://ageofnotes.com/tutorials/setting-age-empires-2-multiplayer-wine-linux-2019/

**Comment by DjSapsan** [comment]
Thanks, backup is a good idea. What about symbolic links im not sure. I'll try today. Actually i used your tutorial for Linux and slightly optimized it. Also i begin to compose .sh script for automatic deployment. One problem is that hotkeys are did not imported from steam, so i copied them manually (im two places, for regular aoc and for WC). Also numpad keys don't working. All this issues ill try to solve by myself.

**Comment by gregstein** [comment]
Np! You can check this guide for symbolic linking https://www.shellhacks.com/symlink-create-symbolic-link-linux/

The WK Installer as well as aoe2tools use sym links you can check x3 Tech mod folder how are they implemented then mimic that in your shell script.

Concerning hotkeys, You should recommend the user run age of empires 2 HD before importing their custom hotkeys, why? Upon the completion of AoE2HD installation; there are no hotkeys yet. User must run the game so his custom hotkeys are downloaded from steam cloud.

However, If they wish to install the standard HD hotkeys they can use "AoE2Tools > Hotkeys". I have fixed a problem in the latest version AoE2Tools (we had the wrong hki file in aoe2tools files which explains hd hotkeys not installing). Also Hotkeys Tool was improved to install hotkeys in a clean way by resetting the entire profile. 

And don't forget to recommend backing up the hotkeys - after they are successfully installed - through
![hotkeysbackup](https://user-images.githubusercontent.com/16618729/66130739-1d686680-e5ea-11e9-9870-4520243d65fc.png)

Then restore from the 'Restore' button which restores hotkeys to AoC, WK and Realms mods at once.

**Comment by DjSapsan** [comment]
please delete it as it is not relevant anymore
